# Continuous integration with travis
language: r
sudo: required

# cache packages to speed up builds
cache: packages

# Check code test coverage
r_packages:
 - covr
after_success:
 - Rscript -e 'library(covr);codecov()'
