# Continuous integration with travis
language: r


# cache packages to speed up builds
cache: packages

# Check code test coverage
r_github_packages:
  - jimhester/covr
after_success:
  - Rscript -e 'library(covr);codecov()'
